# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled
gpus: 1                     # Multi-gpu is not implemented on this branch
guidance_target: 'null'

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 5
sample_every_val: 4
val_check_interval: null
samples_to_generate: 0       # We advise to set it to 2 x batch_size maximum
samples_to_save: 20
chains_to_save: 1
log_every_steps: 50
number_chain_steps: 50        # Number of frames in each gif
regressor_path: /home/asthana/PhD/DiGress/src/outputs/2023-04-26/regressor_nasbench201/checkpoints/regressor/last.ckpt
use_regressor: True
diffusion_path: /home/asthana/Documents/DiGress/DiGress/src/outputs/2024-01-18/17-38-08/checkpoints/graph-tf-model/last-v1.ckpt

final_model_samples_to_generate: 1920
final_model_samples_to_save: 30
final_model_chains_to_save: 20

evaluate_all_checkpoints: False
